#!/usr/bin/env node
// =============================================================================
// Build script: combine the KLITE RPmod source files into a single usermod.
//
// Esolite's mod manager imports one JS file, so we concatenate:
//   1. KLITE-RPmod_ALPHA.js        (main mod: panels, chars, roles, tools)
//   2. KLITE-RPmod_GuidedRP.js     (guided onboarding wizard)
//   3. KLITE-RPmod_Worlds.js       (Worlds engine)
//   4. KLITE-RPmod_WorldsUI.js     (Worlds node-graph editor + panel)
//
// Each source is already a self-contained IIFE. We wrap each in try/catch so a
// runtime failure in one module cannot prevent the others from loading. Output:
//   KLITE-RPmod.js
//
// Usage:  node build_KLITE-RPmod.js
// Re-run after editing any source file.
// =============================================================================
const fs = require('fs');
const path = require('path');

const DIR = __dirname;
const OUT = path.join(DIR, 'KLITE-RPmod.js');

// Order matters only loosely: engine before its UI. Everything else waits on
// window globals / the load event, so relative order is not critical.
const MODULES = [
    { file: 'KLITE-RPmod_ALPHA.js',    name: 'KLITE RPmod (ALPHA core)' },
    { file: 'KLITE-RPmod_GuidedRP.js', name: 'Guided RP (onboarding)' },
    { file: 'KLITE-RPmod_Worlds.js',   name: 'Worlds engine' },
    { file: 'KLITE-RPmod_WorldsUI.js', name: 'Worlds editor UI' },
];

function banner(text) {
    const line = '='.repeat(77);
    return `// ${line}\n// ${text}\n// ${line}\n`;
}

let out = '';
out += banner('KLITE RPmod - combined usermod bundle');
out += `// Generated by build_KLITE-RPmod.js on ${new Date().toISOString()}\n`;
out += '// Do not edit this file directly - edit the source modules and re-run the build.\n';
out += `// Modules (in load order): ${MODULES.map(m => m.file).join(', ')}\n\n`;

let total = 0;
for (const mod of MODULES) {
    const p = path.join(DIR, mod.file);
    if (!fs.existsSync(p)) {
        console.error(`! missing source: ${mod.file} - skipped`);
        continue;
    }
    const src = fs.readFileSync(p, 'utf8');
    total += Buffer.byteLength(src);
    out += banner(`MODULE: ${mod.name}  (${mod.file})`);
    // Wrap so a runtime throw in one module doesn't abort the whole bundle.
    out += `try {\n\n${src}\n\n} catch (e) { try { console.error('[KLITE-RPmod bundle] module failed:', ${JSON.stringify(mod.file)}, e); } catch (_) {} }\n\n`;
    console.log(`+ ${mod.file.padEnd(28)} ${(Buffer.byteLength(src) / 1024).toFixed(0)} KB`);
}

fs.writeFileSync(OUT, out, 'utf8');
console.log(`\n= wrote ${path.basename(OUT)}  (${(Buffer.byteLength(out) / 1024).toFixed(0)} KB from ${(total / 1024).toFixed(0)} KB sources)`);
