#!/usr/bin/env node
// =============================================================================
// Icon set: copies the Lucide icons RPmod uses (dev dependency `lucide-static`,
// ISC; a few icons derived from Feather, MIT) into src/shell/icons.js as element
// data, with the full licence notice as a legal comment so it survives bundling.
// The generated file is committed: `npm run build` needs no network or node_modules
// beyond esbuild, and the usermod stays fully offline.
//
// Usage:  npm run icons   (after changing NAMES or upgrading lucide-static)
// =============================================================================
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PKG = path.join(ROOT, 'node_modules', 'lucide-static');
const OUT = path.join(ROOT, 'src', 'shell', 'icons.js');

// Lucide name -> used for
const NAMES = {
    'columns-3': 'top-bar RPmod button (two side panels around the chat)',
    'x': 'close',
    'chevron-left': 'hide/show panels',
    'chevron-right': 'hide/show panels',
    'chevron-down': 'collapsible sections',
    'maximize-2': 'maximize window',
    'minimize-2': 'restore window',
    'circle-help': 'Guide',
    'book-open': 'open the Guide',
    'arrow-left': 'back',
    'arrow-right': 'next',
    'play': 'Quick Start',
    'id-card': 'character sheet',
    'layout-grid': 'character gallery',
    'eye': 'preview what the AI sees',
    'plus': 'add',
    'sparkles': 'example world',
    'upload': 'import',
    'download': 'export',
    'scroll-text': 'quest log',
    'swords': 'combat',
    'store': 'shop (vendors, R4 extras)',
    'coins': 'sell to a vendor / purse',
    'moon': 'long rest (Party section)',
    'wand-sparkles': 'cast a spell (Combat window)',
    'book-marked': 'Compendium (right dock)',
    'workflow': 'world editor (node graph)',
    'trash-2': 'delete',
    'lock': 'hidden',
    'castle': 'faction headquarters',
    'map-pin': 'location',
    'dice-5': 'roll',
    'rotate-ccw': 'reset',
    'check': 'commit',
    'arrow-left-right': 'swap',
    'door-open': 'dungeon (map editor, doors)',
    'house': 'town (map editor)',
    'mouse-pointer-2': 'map editor: select tool',
    'link-2': 'map editor: connect tool',
    'map': 'mini-map / Map window',
    'search': 'Search the room (map)',
    'wand-sparkles': 'Generate a dungeon or town',
    'dices': 'new random seed (generator)',
    'footprints': 'zone combat: move',
    'wind': 'zone combat: flee',
    'shield': 'zone combat: take cover',
    'eye-off': 'zone combat: hide',
    'circle-dot': 'Guide: zone combat diagrams',
    'pencil': 'quick replies: edit',
    'arrow-up': 'quick replies: move up',
    'message-square': 'quick replies: a reply that sends',
};

const pkg = JSON.parse(fs.readFileSync(path.join(PKG, 'package.json'), 'utf8'));
const licence = fs.readFileSync(path.join(PKG, 'LICENSE'), 'utf8').trim().replaceAll('*/', '* /');

const ATTR = /([a-zA-Z-]+)="([^"]*)"/g;
function parse(name) {
    const svg = fs.readFileSync(path.join(PKG, 'icons', name + '.svg'), 'utf8');
    const body = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'));
    const out = [];
    for (const m of body.matchAll(/<(path|circle|rect|line|polyline|polygon|ellipse)\b([^>]*)\/?>/g)) {
        const attrs = {};
        for (const a of m[2].matchAll(ATTR)) attrs[a[1]] = a[2];
        out.push([m[1], attrs]);
    }
    if (!out.length) throw new Error('no shapes in ' + name);
    return out;
}

const lines = [
    '/*! Icons: Lucide v' + pkg.version + ' (https://lucide.dev), subset used by KLITE RPmod.',
    '',
    licence,
    '*/',
    '// GENERATED by scripts/build-icons.js from lucide-static — do not edit; run `npm run icons`.',
    '// Each icon is a list of [tag, attributes] for a 24×24, stroke-based SVG (see dom.js icon()).',
    'export const LUCIDE = {',
];
for (const [name, use] of Object.entries(NAMES)) {
    lines.push(`    // ${use}`);
    lines.push(`    ${JSON.stringify(name)}: ${JSON.stringify(parse(name))},`);
}
lines.push('};', '');
fs.writeFileSync(OUT, lines.join('\n'));
console.log(`= wrote ${path.relative(ROOT, OUT)} (${Object.keys(NAMES).length} icons, lucide-static ${pkg.version})`);
